config/routes.rb
Rails.application.routes.draw do


  root 'static#homepage'
  get '/contact', to: "static#contact"
  get '/team', to: "static#team"
  post '/button', to: "gossips#like"
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :cities, only: [:index, :show]
  resources :users, only: [:new, :create, :show] do
    resources :gossips do
      resources :likes, only: [:create, :destroy]
      resources :authors, only: [:show]
      resources :comments do
        resources :undercomment
      end
    end
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true
  belongs_to :author, class_name: "User"
  belongs_to :gossip
  has_many :undercomments
  has_many :likes
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authorized, only: [:update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(author: User.find(params[:user_id]), gossip: Gossip.find(params[:gossip_id]))
    @comment.content = comment_params.values[0]
    if @comment.save
      redirect_to user_gossip_comments_path(params[:user_id], params[:gossip_id])
    else
      render "new"
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to user_gossip_comment_path(params[:user_id], params[:gossip_id], params[:id])
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to user_gossip_comments_path(params[:user_id], params[:gossip_id]), notice: "The comment has been deleted correctly"
  end

    private

    def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end

    def authorized
      unless current_user == @comment.author
      flash[:danger] = "Don't touch other people's sh*t!"
      redirect_to user_gossip_comment_path(params[:user_id], params[:gossip_id], params[:id])
      end
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<body>

    <div class="card">
      <div class="card-header">
        Comment n°<%= params[:id] %>
        On Gossip n°<%= params[:gossip_id] %>, <%= Gossip.find(params[:gossip_id]).title %>, written by <%= Gossip.find(params[:gossip_id]).author.first_name %>
      </div>
      <div class="card-body">
        <%= link_to "#{@comment.author.first_name}", user_gossip_author_path(params[:user_id],params[:gossip_id],@comment.author.id) %> said:
        <p class="card-text"><%= @comment.content %></p>
      </div>
    </div>
  
    <div class="card">
      <div class="card-body">
        <%= form_for @comment, url: {action: 'update'} do |comment| %>
  
          <div class = "form-group">
            <label>New Content</label>
            <%= comment.text_area :content, class: 'form-control' %>
          </div>
  
          <div class = "form-group">
            <button type = "submit" class = "btn btn-dark btn-sm"> Edit Comment </button>
          </div>
  
        <% end %>
      </div>
    </div>

    <div class ="button-box col-lg-12" id="end-box">
      <br />
      <%= link_to "Back to Comment", user_gossip_comment_path(params[:user_id],params[:gossip_id], params[:id]), :class => "btn btn-primary btn-lg" %>
    </div>
    <div class ="button-box col-lg-12" id="end-box">
      <br />
      <%= link_to "Back to Comments", user_gossip_comments_path(params[:user_id],params[:gossip_id]), :class => "btn btn-primary btn-lg" %>
    </div>
  
  </body>
    

app/views/comments/index.html.erb
<body>

  <p id="notice"><%= notice %></p>
  <div class="card">
    <div class="card-header" >
      Gossip n°<%= params[:gossip_id] %>: <%= Gossip.find(params[:gossip_id]).title %>
    </div>
    <div class="card-header" >Comments</div>
  </div>
  <br />
  <div class="container h-100 d-flex justify-content-center">
    <div class="card-columns">
      <% @comments.where("gossip_id = ?", params[:gossip_id]).each do |comment|%>
        <div class="card" style="width: 22rem">
          <div class="card-body">
            <h5 class="card-title"><%=comment.author.first_name%> says:</h5>
            <p class="card-text"><%=comment.content%></p>
            <%= link_to "Interract", user_gossip_comment_path(params[:user_id],params[:gossip_id],comment.id), :class => "btn btn-sm btn-dark" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <% if @comments.where("gossip_id = ?", params[:gossip_id]).size > 3 %>
    <div class = "btns-bottom">
      <br />
      <%= link_to 'New Comment', new_user_gossip_comment_path(params[:user_id],params[:gossip_id]), :class => "btn btn-secondary btn-lg"%>
      <br />
      <%= link_to "Back to Gossip", user_gossip_path(params[:user_id],params[:gossip_id]), :class => "btn btn-secondary btn-lg" %>
    </div>
  <% else %>
    <div class ="button-box col-lg-12" id="end-box">
      <br />
      <%= link_to 'New Comment', new_user_gossip_comment_path(params[:user_id],params[:gossip_id]), :class => "btn btn-primary btn-lg"%>
    </div>
    <div class ="button-box col-lg-12" id="end-box">
      <br />
      <%= link_to "Back to Gossip", user_gossip_path(params[:user_id],params[:gossip_id]), :class => "btn btn-primary btn-lg" %>
    </div>
  <% end %>

</body>

app/views/comments/new.html.erb
<body>

  <div class="alert alert-danger" role="alert">
    <% if @comment.errors.any? %>
      <p>Comment could not be created for the following reasons :</p>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="card">
      <div class="card-body">
        <%= form_for @comment, url: {action: 'create'} do |comment| %>
  
          <div class = "form-group">
            <label>Content</label>
            <%= comment.text_area :content, class: 'form-control' %>
          </div>
  
          <div class = "form-group">
            <button type = "submit" class = "btn btn-dark btn-sm"> Create Comment </button>
          </div>
  
        <% end %>
      </div>
    </div>

  <div class ="button-box col-lg-12" id="end-box">
    <br />
    <%= link_to "Back to Comments", user_gossip_comments_path(params[:user_id],params[:gossip_id]), :class => "btn btn-primary btn-lg" %>
  </div>
  <div class ="button-box col-lg-12" id="end-box">
    <br />
    <%= link_to "Back to Gossip", user_gossip_path(params[:user_id],params[:gossip_id]), :class => "btn btn-primary btn-lg" %>
  </div>

</body>

app/views/comments/show.html.erb
<body>

  <div class="card">
    <div class="card-header" >
      Comment n°<%= params[:id] %>
      On Gossip n°<%= params[:gossip_id] %>, <%= Gossip.find(params[:gossip_id]).title %>, written by <%= Gossip.find(params[:gossip_id]).author.first_name %>
    </div>

    <div class="card-body">
      <%= link_to "#{@comment.author.first_name}", user_gossip_author_path(params[:user_id],params[:gossip_id],@comment.author.id) %> said:
      <p class="card-text"><%= @comment.content %></p>
      
      <div class ="button-box col-lg-12" id="edit-stuff">
        <% if @comment.author.id == session[:user_id] %>
          <div><%= link_to "Edit Comment", edit_user_gossip_comment_path(params[:user_id],params[:gossip_id],@comment), :class => "btn btn-success btn-sm" %></div>
          <div><%= link_to "Delete Comment", user_gossip_comment_path(params[:user_id],params[:gossip_id],@comment), method: :delete, data:{ confirm: "Are you sure you want to delete this comment?"}, :class => "btn btn-danger btn-sm"%></div>
        <% end %>
        <div><%= link_to "Comment Comment", user_gossip_comment_undercomment_index_path(params[:user_id],params[:gossip_id],@comment),:class => "btn btn-dark btn-sm"%></div>
      </div>

    </div>
  </div>

  <div class ="button-box col-lg-12" id="end-box">
    <br />
    <%= link_to "Back to Comments", user_gossip_comments_path(params[:user_id],params[:gossip_id]), :class => "btn btn-primary btn-lg" %>
  </div>

  <div class ="button-box col-lg-12" id="end-box">
    <br />
    <%= link_to "Back to Gossip", user_gossip_path(params[:user_id],params[:gossip_id]), :class => "btn btn-primary btn-lg" %>
  </div>

</body>