config/routes.rb
Rails.application.routes.draw do


  root 'static#homepage'
  get '/contact', to: "static#contact"
  get '/team', to: "static#team"
  post '/button', to: "gossips#like"
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :cities, only: [:index, :show]
  resources :users, only: [:new, :create, :show] do
    resources :gossips do
      resources :likes, only: [:create, :destroy]
      resources :authors, only: [:show]
      resources :comments do
        resources :undercomment
      end
    end
  end
  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title,
		presence: true,
		length: { in: 3..14 }

	validates :content,
		presence: true

  belongs_to :author, class_name: "User"
  has_many :comments
  has_many :likes
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:create, :new, :destroy, :show, :index]
  before_action :authorized, only: [:update, :destroy]

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], author: User.find(params[:user_id]))

    if @gossip.save
      redirect_to user_gossips_path(params[:user_id])
    else
      render "new"
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(new_gossip)
      redirect_to user_gossip_path(params[:user_id],@gossip.id)
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to user_gossips_path(params[:user_id]), notice: "The Gossip #{@gossip.title} has been deleted correctly."
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  def authorized
    unless current_user == Gossip.find(params[:id]).author
    flash[:danger] = "Don't touch other people's sh*t!"
    redirect_to user_gossip_path(params[:user_id], params[:id])
    end
  end

  def new_gossip
    params.require(:gossip).permit(:title, :content)
  end

end

app/views/gossips/edit.html.erb
<body>

  <div class="card">
    <div class="card-header">
      Gossip n°<%= params[:id] %>: <%= @gossip.title %>
    </div>
    <div class="card-body">
      Author: <%= link_to "#{@gossip.author.first_name}", user_gossip_author_path(params[:user_id],params[:id],@gossip.author.id) %> 
      <p class="card-text">Content: <%= @gossip.content %></p>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <%= form_for @gossip, url: {action: 'update'} do |gossip| %>

        <div class = "form-group">
          <label>New Title</label>
          <%= gossip.text_field :title, class: 'form-control' %>
        </div>

        <div class = "form-group">
          <label>New Content</label>
          <%= gossip.text_area :content, class: 'form-control' %>
        </div>

        <div class = "form-group">
          <button type = "submit" class = "btn btn-dark btn-sm"> Edit Gossip </button>
        </div>

      <% end %>
    </div>
  </div>

</body>

<!-- <div class="card">
  <div class="card-body">
    <form action= <%= user_gossip_path %> method="post">
      <input name="utf8" type="hidden" value="&#x2713;" />
      <input type='hidden' name="_method" value="patch" >
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
      <p>New Title : <input type='text' name='gossip[title]' value= <%= @gossip.title %> ></p>
      <p>New Author : <input type='text' name='gossip[author]' value= <%= @gossip.author.first_name %>></p>  
      <p>New Content : <input type='text' name='gossip[content]'><br/></p>
      <input class= "btn btn-primary btn-sm" type='submit'/>
    </form>
  </div>
</div> -->

app/views/gossips/index.html.erb
<body>

  <div class="container h-50">
    <div class="card-columns" style="max-height: 50%">
      <% @gossips.each do |gossip|%>
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title" style="white-space: nowrap"><%=gossip.author.first_name%>'s gossip</h5>
              <p class="card-text"style="white-space: nowrap"><%=gossip.title%></p>
              <% if gossip.likes.size > 0 %>
                <p class = "card-text"><%= gossip.likes.size %> 💖</p>
              <% end %>
              <%= link_to "Check it out", user_gossip_path(params[:user_id],gossip.id), :class => "btn btn-dark" %>
              <% @current_gossip_id = gossip.id %>
              <%= button_to '💖 LIKE 💖', user_gossip_likes_path(params[:user_id], gossip.id, :url => "gossip_index"), method: :post, class: "btn btn-dark" %>
            </div>
          </div>
      <% end %>
    </div>
  </div>

</body>

app/views/gossips/new.html.erb
<body>  

  <div class="alert alert-danger" role="alert">

    <% if @gossip.errors.any? %>
      <p>Gossip could not be created for the following reasons :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    
  </div>
  
  <div class="card">
    <div class="card-body">
      <%= form_tag url_for(action: 'create'), method: "post" do %>

        <%= label_tag 'Title' %>
        <%= text_field_tag 'title', @gossip.title, :class => "form-control" %>
        <br />

        <%= label_tag 'Content' %>
        <%= text_area_tag 'content', @gossip.content, :class => "form-control" %>
        <br /> <br />

        <%= submit_tag "Create Gossip", :class => "btn btn-dark btn-sm" %>

      <% end %>
    </div>
  </div>

</body>

app/views/gossips/show.html.erb
<body>

  <div class="card">
    <div class="card-header" >
      Gossip n°<%= params[:id] %>: <%= @gossip.title %>
    </div>

    <div class="card-body">

      Author: <%= link_to "#{@gossip.author.first_name}", user_gossip_author_path(params[:user_id],params[:id],@gossip.author.id) %> 
      <p class="card-text">Content: <%= @gossip.content %></p>
      <% if @gossip.likes.size > 0 %>
        <p class = "card-text"><%= @gossip.likes.size %> 💖</p>
      <% end %>

      <div class ="button-box col-lg-12" id="edit-stuff">
        <%= button_to '💖 LIKE 💖', user_gossip_likes_path(params[:user_id], @gossip.id), method: :post, class: "btn btn-dark btn-sm" %>
        <% likes = Like.where("gossip_id = ? AND author_id = ?", @gossip.id, params[:user_id]) %>
        <% if likes.size > 0 %>
          <%= button_to '💔 UNLIKE 💔', user_gossip_like_path(params[:user_id], @gossip.id, likes.last.id), method: :delete, class: "btn btn-dark btn-sm" %>
        <% end %>
      </div>
    
      <div class ="button-box col-lg-12" id="edit-stuff">
        <% if session[:user_id] == @gossip.author.id %>
          <div><%= link_to "Edit this Gossip", edit_user_gossip_path(params[:user_id],params[:id]), :class => "btn btn-success btn-sm" %></div>
          <div><%= link_to "Delete this Gossip", user_gossip_path(params[:user_id],params[:id]), method: :delete, data:{ confirm: "Are you sure you want to delete this gossip?"}, :class => "btn btn-danger btn-sm"%></div>
        <% end %>
      </div>

    </div>
  </div>
      
  <div class ="button-box col-lg-12" id="end-box">
    <br />
    <%= link_to "Read Comments (#{@gossip.comments.size})", user_gossip_comments_path(params[:user_id],params[:id]), :class => "btn btn-primary btn-lg" %>
  </div>
  <div class ="button-box col-lg-12" id="end-box">
    <br />
    <%= link_to 'New Comment', new_user_gossip_comment_path(params[:user_id],params[:id]), :class => "btn btn-primary   btn-lg" %>
  </div>

</body>