config/routes.rb
Rails.application.routes.draw do


  root 'static#homepage'
  get '/contact', to: "static#contact"
  get '/team', to: "static#team"
  post '/button', to: "gossips#like"
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :cities, only: [:index, :show]
  resources :users, only: [:new, :create, :show] do
    resources :gossips do
      resources :likes, only: [:create, :destroy]
      resources :authors, only: [:show]
      resources :comments do
        resources :undercomment
      end
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true
  belongs_to :author, class_name: "User"
  belongs_to :gossip
  has_many :undercomments
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title,
		presence: true,
		length: { in: 3..14 }

	validates :content,
		presence: true

  belongs_to :author, class_name: "User"
  has_many :comments
  has_many :likes
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :comment, optional: true
  belongs_to :author, class_name: "User"
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :private_message_recipients
  has_many :recipients, through: :private_message_recipients, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/undercomment.rb
class Undercomment < ApplicationRecord
  belongs_to :comment
  belongs_to :author, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email,
    presence: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "adress please" }
  validates :password, presence: true
  validates :age, presence: true

  has_many :written_gossips, foreign_key: 'author_id', class_name: "Gossip"
  has_many :written_comments, foreign_key: 'author_id', class_name: "Comment"
  has_many :written_undercomments, foreign_key: 'author_id', class_name: "Undercomment"
  has_many :sent_likes, foreign_key: 'author_id', class_name: "Like"
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :private_message_recipients
  has_many :received_messages, through: :private_message_recipients, class_name: "PrivateMessage"
  belongs_to :city, optional: true
  has_secure_password

  class << self
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Paswword.create(string, cost: cost)
    end

    def User.new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end 

  def authenticated?(remmember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end


end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:string, :string)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user, only: [:create]

  def create
    @like = Like.new(gossip_id: params[:gossip_id], author_id: params[:user_id])
    @like.save
    if params[:url] == "gossip_index"
      redirect_to user_gossips_path(params[:user_id])
    else
      redirect_to user_gossip_path(params[:user_id], params[:gossip_id])
    end
  end
  

  def destroy
    Like.find(params[:id]).destroy
    redirect_to user_gossip_path(params[:user_id], params[:gossip_id])
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
 
  def show
    @user = User.find(session[:user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(new_user)
    @user.city_id = params[:city_id]
    if @user.save
      session[:user_id] = @user.id
	    redirect_to user_gossips_path(session[:user_id])
    else
      render "new"
    end
  end

  private

  def new_user
    params.require(:user).permit(:first_name, :last_name, :email, :password, :age, :description)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_helper.rb
module DynamicHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
  	user.remember
  	cookies.permanent.signed[:user_id] = user.id
  	cookies.permanent[:remember_token] = user.remember_token
  end 

  def logged_in?
  	!current_user.nil?
  end

  def forget(user)
  	user.forget
  	cookies.delete(:user_id)
  	cookies.delete(:remember_token)
x end

  def log_out
  	forget(current_user)
  	session.delete(:user_id)
  	@current_user = nil
  end


end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/undercomments_helper.rb
module UndercommentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300" type="text/css" />

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="/application.css" type="text/css">
    <%= stylesheet_link_tag    'application', media: 'all'%>


  </head>

  <body>
    <div class="head">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <!-- <a class="navbar-brand" href="#"></a> -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto" id="head1">
              
              <% if session[:user_id] != nil %>
                <li class="nav-item">
                  <%= link_to user_gossips_path(session[:user_id]), :class => "nav-link" do %>
                    <i class="glyphicon glyphicon-home"></i> 
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                </li>
              <% end %>

              <li class= "nav-item">
                <%= link_to "Team", team_path, :class => "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Contact", contact_path, :class => "nav-link" %>
              </li>

              <% if session[:user_id] != nil %>
                <li>
                  <%= link_to "New Gossip", new_user_gossip_path(session[:user_id]), :class => "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Profile", user_id_path(session[:user_id]), method: "get", :class => "nav-link" %>
                </li>
                <li class="nav-item", id='disconnect'>
                  <%= link_to "Disconnect", session_path(session), method: "delete", :class => "nav-link" %>
                </li>

              <% end %>

              
            </ul>
          </div>


          <div id="head2">
            <% if session[:user_id] != nil %>
              <div>
                <h1 class="display-4" style="font-family: fantasy">Welcome <%=current_user.first_name%> </h1>
                <!-- <p class = "display-5" style="font-size: 14px">Check out our gossips >>></p> -->
              </div>
            <% else %>
              <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav mr-auto" id="head1">
                    <li class="nav-item">
                      <%= link_to "Login", new_session_path, :class => "nav-link" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "Signup", new_user_path, :class => "nav-link" %>
                    </li>
                </ul>
              </div>
            <% end %>
          </div>

        </nav>
        <%= yield %>
      </div>

      
        
    </div>

    <footer>
      <% if params[:user_id] != nil && request.env['PATH_INFO'] != user_gossips_path(params[:user_id]) %>
        <div class ="button-box col-lg-12" style="border: black"><%= link_to "Back to Gossip List", user_gossips_path(params[:user_id]), :class => "btn btn-primary btn-lg" %></p>
      <% end %>
    </footer>
  </body>
</html>